framework:
    messenger:
        adapters:
          rsvp:
            dsn: "%env(MESSENGER_ADAPTER_DSN)%"
            options:
              -
                name: exchange
                value:
                  name: rsvp
        routing:
          'App\Entity\RSVP': messenger.sender.rsvp
