framework:
    messenger:
        adapters:
          rsvp:
            dsn: "%env(MESSENGER_ADAPTER_DSN)%"
            options:
              auto-setup: 'false'
              exchange:
                name: rsvp
        serializer:
          context:
            enable_max_depth: true
            groups:
              - 'read'
        routing:
          'App\Entity\RSVP': messenger.sender.rsvp
