version: '3'
services:
  web:
    links:
      - smtp
      - database
      - messenger
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
  database:
    image: mariadb:10.1
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
  messenger:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    volumes:
      - messenger-data:/var/lib/rabbitmq
volumes:
  db-data:
  messenger-data:
