version: '3'
services:
  web:
    links:
      - smtp
    ports:
      - 8888:80
  # cache:
  #   ports:
  #     - 8888:80
  smtp:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
volumes:
  db-data:
