wedding_respond_homepage:
    path:  /
    defaults: { _controller: WeddingRespondBundle:Default:index }

wedding_respond_songs:
    path:  /songs
    defaults: { _controller: WeddingRespondBundle:Default:songs }
    
wedding_respond_rehearsal:
    path:  /rehearsal
    defaults: { _controller: WeddingRespondBundle:Rehearsal:index }

wedding_respond_rehearsal_catch:
  path: /{rehearsal}
  defaults:
    _controller: FrameworkBundle:Redirect:urlRedirect
    path: /rehearsal
    permanent: true
  requirements:
    rehearsal: (?i:rehearsal)