wedding_respond_homepage:
    pattern:  /
    defaults: { _controller: WeddingRespondBundle:Default:index }

wedding_respond_songs:
    pattern:  /songs
    defaults: { _controller: WeddingRespondBundle:Default:songs }
    
wedding_respond_rehearsal:
    pattern:  /rehearsal
    defaults: { _controller: WeddingRespondBundle:Rehearsal:index }