# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    bride:
      '%env(BRIDE_EMAIL)%': '%env(BRIDE_NAME)%'
    groom:
      '%env(GROOM_EMAIL)%': '%env(GROOM_NAME)%'
    site:
      '%env(SITE_EMAIL)%': '%env(SITE_NAME)%'
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    app.controller_respond:
      public: true
      class: App\Controller\RespondController
      arguments:
        - '@doctrine'
        - '@mailer'
        - '@twig'
        - '@message_bus'
        - '%site%'
        - '%bride%'
        - '%groom%'
